@startuml
title Процесс бронирования инвентаря

start
:вывод: Выбирайте инвентарь;
:вывод: Выберите количество;

repeat
  if (Есть столько ли в наличии?) then (да)
    :Счётчик -N в базе;
    break
  else (нет)
    :вывод: Нет в наличии, выберите другое количество;
  endif
repeat while (нет)

:вывод: Выберите время брони;

repeat
  if (Возможна ли бронь на это время?) then (да)
    :Счётчик -N в базе;
    :Создать бронь;
    :вывод: Бронь успешна!;
    break
  else (нет)
    :вывод: Не возможно забронировать, выберите другое время;
  endif
repeat while (нет)

stop
@enduml