@startuml
title Процесс выдачи единицы

start
:Авторизация;
:Поиск информации в базе;

if (Есть ли свободная единица) then (да)
  :Счетчик -1;
  :Вывод: можно взять;
  :Указать дата-время взятия;
  :Указать дата-время возврата;
  :Отзыв;
else (нет)
  :Вывод: нет в наличии;
endif

end
@enduml